### PR TITLE
Update this to API 4.0.0.

### PR DESCRIPTION
**Pull request by DarkWav**
I updated this for the latest dev build of PMMP featuring API 4.0.0, I thought you might want to merge this.
I Changed the following:
No functionallity changes.
Internal code changes:
+ Correctly converted onRun() to void.
+ Hacked arround the onCompletion() void enforcement.
+ Fixed AsyncTasks.
+ Updated API to 4.0.0.
**WARNING: THIS VERSION DOES NOT WORK WITH API 3.0.0 ANY MORE!!!**

### CODE REVIEW

**Comment by teracube** [comment]
@DarkWav 
test OK running with PocketMine-MP version 4.0.0+dev.1529
good job . thanks ; -)

**Comment by DarkWav** [comment]
@teracube i can also upgrade InvSee for you if you want.

**Comment by teracube** [comment]
yes i want
thanks :-)

**Comment by DarkWav** [comment]
the bad news is that cannot upgrade most plugins as of licensing issues.

**Comment by teracube** [comment]
oooh no
thanks darku

**Comment by HiddenMotives** [comment]
Good Work once again!

**Pull request merged**
