### PR TITLE
Update this to PocketMine-API 3.0.0 and newer.

### PR DESCRIPTION
**Pull request by DarkWav**
I updated the plugin so it will run on PocketMine-API 3.0.0 or newer.
If you wish to merge this PR you can of course do it, or update the plugin yourself :)

### CODE REVIEW

**Comment by teracube** [comment]
i tested it and it's work 
thanks

**Comment by HiddenMotives** [comment]
Good Work!

**Comment by teracube** [comment]
@DarkWav 
@HiddenMotives 

could you please upgrade VPNGuard on API 4.0.0

```
PocketMine-MP Crash Dump Sun Oct 7 09:21:44 CEST 2018

Error: Declaration of basprohop\libraries\Async::onRun() must be compatible with pocketmine\scheduler\AsyncTask::onRun(): void
File: VPNGuard_v1.0.7.phar/src/basprohop/libraries/Async
Line: 221
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: VPNGuard v1.0.7

Code:
[212]                   $player->sendMessage("Lat: " . $locationLat . ", Long:" . $locationLong);
[213]                 }
[214]               }
[215]             } else {
[216]               $player->sendMessage("API Server Returned Error Message: " . $obj["msg"]);
[217]             }
[218]           }
[219]         }
[220]     }
[221] }
[222] 
[223] 
[224] 
[225] 
[226] 
[227] 
[228] 
[229] 
[230] 
[231] 

```

**Comment by DarkWav** [comment]
@teracube i'm working on it, thanks for notifying

**Comment by DarkWav** [comment]
Take a look at PR #16.
Until its merged, you can use https://github.com/DarkWav/VPNGuard.

**Comment by teracube** [comment]
@DarkWav
test OK running with PocketMine-MP version 4.0.0+dev.1529
good job . thanks ; -)

**Pull request merged**
